language: bash

services: docker

os: windows

install:
  - docker version
  - env | sort
  - export IMAGE_NAME=$(grep imagename= Dockerfile | sed -e 's/.*imagename="\(.*\)".*/\1/')
  - echo IMAGE_NAME=$IMAGE_NAME
  - export IMAGE_VERSION=$(grep version= Dockerfile | sed -e 's/.*version="\(.*\)".*/\1/')
  - echo IMAGE_VERSION=$IMAGE_VERSION
  - export IMAGE="$ORGANISATION_NAME/$IMAGE_NAME"
  - echo IMAGE=$IMAGE
  - docker build --pull -t $IMAGE:$IMAGE_VERSION .
  - docker images

script:
  - echo "LOGIN TO HUB.DOCKER"
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo "PUSH HUB.DOCKER"
  - docker push $IMAGE:$IMAGE_VERSION
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker tag $IMAGE:$IMAGE_VERSION $IMAGE:latest && docker push $IMAGE:latest; fi
#  - echo "UPDATE README IN HUB.DOCKER"
#  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker run --pull --rm -v $(pwd):/data/ aemdesign/dockerhub-description "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$IMAGE"; fi
#  - if [[ $TRAVIS_BRANCH == "master" ]]; then ./dockerhub.sh "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$IMAGE" "README.md"; fi
